# Generated by Django 4.2.3 on 2023-08-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Course',
            new_name='course',
        ),
    ]
